### ISSUE TITLE
validation for only month/year

### ISSUE THREAD

**Issue by h3n0r1k** [lsgs/redcap-date-validation-action-tags#1]
hello,

thanks for the awesome modul! Would it be possible to make this working for a custom date validation type with month.year only?  i.E.   10.2019 or 12.2020.

Br

**Comment by lsgs** [comment]
I've got some ideas fro extending this to other field types so comparison values can be piped in - e.g. for cross-field validation checks. I'm not sure about for custom validation types though.

**Comment by h3n0r1k** [comment]
okay, thanks. sounds great!
