### ISSUE TITLE
Error Message: syntax error, unexpected 'include' (T_INCLUDE)

### ISSUE THREAD

**Issue by croftj01** [lsgs/redcap-date-validation-action-tags#2]
We have recently installed this and have seen the below error message.

[This message was automatically generated by REDCap] 

Could not instantiate the 'date_validation_action_tags' module because of the following error. Stack traces are unfortunately not available for this type of error: 

Error Message: syntax error, unexpected 'include' (T_INCLUDE), expecting identifier (T_STRING) 
File: C:\*path-removed*\modules\date_validation_action_tags_v1.0.0\DateValidationActionTags.php 
Line: 49 

Have you seen his  before?

Many thanks in advance.

**Comment by lsgs** [comment]
Thanks for  the report @croftj01. It's complaining about the word `include` on line 49, which is this one:
`        protected function include($instrument) {`

It seems like it is only from PHP 7 that a keyword like include is allowed as a method name. ([https://www.php.net/manual/en/reserved.keywords.php](https://www.php.net/manual/en/reserved.keywords.php)) Could it be that you are still using PHP 5.x? If you can confirm that I will do an update to the module so it will use a more broadly acceptable method name.

**Comment by croftj01** [comment]
Just checked we are using PHP 7 for that REDCap instance.
Can I check which PHP 7 version you have been using?

Many thanks for the response, it would be great to get this solved.

**Comment by croftj01** [comment]
Bump...

**Comment by lsgs** [comment]
Method include() is renamed in release v1.0.1. Look out for it via the REDCap Repo.
